name: RLCraft Release

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get Tag
        id: tag
        uses: dawidd6/action-get-tag@v1

      - name: Build Image
        run: docker build --tag eu.gcr.io/mc-rlcraft/rlcraft:${{steps.tag.outputs.tag}} .

      - name: Tag Latest
        run: docker tag eu.gcr.io/mc-rlcraft/rlcraft:${{steps.tag.outputs.tag}} eu.gcr.io/mc-rlcraft/rlcraft:latest
      
      - name: Login to GCR
        uses: docker/login-action@v1
        with:
          registry: eu.gcr.io
          username: _json_key
          password: ${{ secrets.GCR_KEY }}
      - name: Push to GCR
        run: docker push eu.gcr.io/mc-rlcraft/rlcraft
