name: RLCraft Tests

on:
  push:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Image
        run: docker build -t rlcraft:${GITHUB_SHA::8} . --file Dockerfile
