name: RLCraft Tests

on:
  push:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Image
        run: docker build --tag eu.gcr.io/mc-rlcraft/rlcraft:${GITHUB_SHA::8} .

      - name: Login to GCR
        uses: docker/login-action@v1
        with:
          registry: eu.gcr.io
          username: _json_key
          password: ${{ secrets.GCR_KEY }}

      - name: Push to GCR
        run: docker push eu.gcr.io/mc-rlcraft/rlcraft
